### ISSUE TITLE
Exception: Method not found, when replacing an image in admin

### ISSUE THREAD

**Issue by Qonstrukt** [cofoundry-cms/Cofoundry.Plugins.Imaging.ImageSharp#2]
The following error is received while replacing a PNG image:

```
Exception: Method not found: ‘!0 System.ReadOnlySpan`1.get_Item(Int32)’.

Stack trace:

at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.IsSupportedFileFormat(ReadOnlySpan`1 header)
at SixLabors.ImageSharp.Formats.Bmp.BmpImageFormatDetector.DetectFormat(ReadOnlySpan`1 header)
at SixLabors.ImageSharp.Image.<>c__DisplayClass0_0.<InternalDetectFormat>b__0(IImageFormatDetector x)
at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
at System.Linq.Enumerable.TryGetLast[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
at SixLabors.ImageSharp.Image.InternalDetectFormat(Stream stream, Configuration config)
at SixLabors.ImageSharp.Image.Decode[TPixel](Stream stream, Configuration config)
at SixLabors.ImageSharp.Image.<>c__DisplayClass43_0`1.<Load>b__0(Stream s)
at SixLabors.ImageSharp.Image.WithSeekableStream[T](Stream stream, Func`2 action)
at SixLabors.ImageSharp.Image.Load[TPixel](Configuration config, Stream stream, IImageFormat& format)
at Cofoundry.Plugins.Imaging.ImageSharp.ImageSharpImageAssetFileService.SaveAsync(IUploadedFile uploadedFile, ImageAsset imageAsset, String propertyName)
at Cofoundry.Domain.UpdateImageAssetCommandHandler.ExecuteAsync(UpdateImageAssetCommand command, IExecutionContext executionContext)
at Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync[TCommand](TCommand command, IExecutionContext executionContext)
at Cofoundry.Domain.CQS.CommandExecutor.ExecuteCommandAsync[TCommand](TCommand command, IExecutionContext executionContext)
at Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command, IExecutionContext executionContext)
at Cofoundry.Domain.CQS.CommandExecutor.ExecuteAsync(ICommand command)
at Cofoundry.Web.ApiResponseHelper.RunCommandAsync[TCommand](Controller controller, TCommand command)
at Cofoundry.Web.Admin.ImagesApiController.Put(Int32 imageAssetId, UpdateImageAssetCommand command, IFormFile file)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
at Cofoundry.Web.AutoUpdateMiddleware.Invoke(HttpContext cx)
at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
at Cofoundry.Plugins.ErrorLogging.ErrorLoggingMiddleware.Invoke(HttpContext context, ILogger`1 logger, IErrorLoggingService errorLoggingService)
```

I'm not sure if ASP.NET Core 2.1 is to blame here.

**Comment by HeyJoel** [comment]
Hi, sorry I didn't have this repo on watch for some reason so missed this.

I'm pretty sure this issue was [resolved in the latest beta of image sharp](https://github.com/SixLabors/ImageSharp/issues/663) so if you upgrade to the latest Cofoundry package is should be resolved.

I had similar issues in one of my sites that used images from a wide range of sources and it has since been resolved. If you are continuing to get issues do let me know.
